### ISSUE TITLE
Clicking logo (navigating to /browse) should only navigate once

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/unified-codes#447]
## Expected Behaviour

Clicking the mSupply logo in the top left takes you back to the browse page. However, if you click it multiple times while on the /browse page, it shouldn't add any more entries to the history.

## Current Behaviour

If you click the logo 4 times, you'd have to click the back arrow 4 times to get back to wherever you were before 😅 

## Possible Solution

Kind of would have thought react-router would de-dupe stuff like this?

**Comment by lache-melvin** [comment]
Perhaps we should wrap the logo in a link tag rather than calling `navigate` - I think this would also give us the functionality of being able to cmd + click on the logo to open the home page in a new tab

**Comment by jmbrunskill** [comment]
> Perhaps we should wrap the logo in a link tag rather than calling `navigate` - I think this would also give us the functionality of being able to cmd + click on the logo to open the home page in a new tab

Ooh yes I like that solution
