### ISSUE TITLE
UI for pending change details

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/unified-codes#480]
Details view for a new product/changes to a product.

Figma details:

https://www.figma.com/file/LOK6QwbB4NQwyWYL68HQ6A/Universal-Codes?type=design&node-id=13-789&mode=design&t=WfiQGC3m8gJKnL7b-0#642671494

When we're adding to an existing drug, will we receive the existing dat a s well, or keep that separate and merge it somehow from the frontend??

**Comment by lache-melvin** [comment]
Will store a separate `PendingChange` object, which once approved calls the `upsert_entity` functionality.

The other option was to put a pending flag on entities, but this prevents us being able to handle pending updates to a node if needed in future.

PendingChanges won't have codes assigned for new nodes.

Might be nice to store stringified JSON of the Pending change as one node, rather than creating a bunch of nodes only to need to remove them again?

Given that upsert_entity does a full overwrite of the existing entity, PendingChange should probably be a full entity too. For edits, perhaps we can have a flag on each node if it is existing or new? (So that we can display the diff in the UI)

**Comment by jmbrunskill** [comment]
> Given that upsert_entity does a full overwrite of the existing entity, PendingChange should probably be a full entity too
This seems like a quite a nice idea, although we can also change what we send from the frontend if we want. Sending the whole thing seemed to be the most logical to me, having something to check if we need to update or if we can skip it might be a nice optimisation?

>For edits, perhaps we can have a flag on each node if it is existing or new? (So that we can display the diff in the UI)
If we're not storing codes we could use the missing code as a flag to say that it's new?

**Comment by lache-melvin** [comment]
> > Given that upsert_entity does a full overwrite of the existing entity, PendingChange should probably be a full entity too
> This seems like a quite a nice idea, although we can also change what we send from the frontend if we want. Sending the whole thing seemed to be the most logical to me, having something to check if we need to update or if we can skip it might be a nice optimisation?
> 
> > For edits, perhaps we can have a flag on each node if it is existing or new? (So that we can display the diff in the UI)
> If we're not storing codes we could use the missing code as a flag to say that it's new?

Have been thinking some more about this - particularly if in future we are opening this up to external submissions, do you think it's important that we support multiple pending changes against one entity? If so, we shouldn't store the full node on the pending change, as the first saved change would be overwritten by the second...

 I'm arriving at storing just the new nodes on the Pending Change (perhaps as an array), and querying for them to merge into/diff against the existing Entity. Each item in the array would have a parent code, so we know where it lives in the diff. If it is a new Entity, the parent code would be the category code. This way if the base entity changes while a change is still pending, those changes won't get lost. Only thing we might need to account for is if two change requests add the same thing? But we have duplication checks in place already so should be fine...

I think the array items could have all their children, as if we're in add only mode then if there is a new node, all children of it will also be new. In future, if we need to update existing nodes, we could probably do that by checking whether of not the node has a code like you mentioned.
