### ISSUE TITLE
Remove old source code

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/unified-codes#494]
Now that the Rust API is connected and running, we should remove the remaining `data-service` folder, and its related scripts/README documentation - we should confirm the v1 API features are all in the Rust API before doing this.

We could also remove the `universal-codes` folder, which contains the source code for the old UI. I don't think we really need this anymore either?

**Comment by mark-prins** [comment]
agree - would be good to tidy up 🙏
