### ISSUE TITLE
Alternative names

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/unified-codes#503]
Alternative names have been provided in the csv file, for example Acetylsalicylic Acid == Aspirin

![Image](https://github.com/msupply-foundation/unified-codes/assets/8287373/c438a1ec-9596-429b-8838-163b9627fbf2)

These aren't loaded into dgraph or available to search.

Acceptance Criteria

- [ ] Alternative names are added to dgraph
- [ ] Alternative names can be added via the new admin UI
- [ ] Searching using an alternative name should find the drug in the Browse page

**Comment by lache-melvin** [comment]
Related: #473

**Comment by lache-melvin** [comment]
Also should be searchable in mSupply
