### ISSUE TITLE
Support drug interactions

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/unified-codes#532]
These are supposed to be supported by UC - there is an endpoint for them, but we didn't have a reliable source for the interaction data so it hasn't been completed.

We should complete this, manually storing our own data set of interactions. 

Requirements:
- Add interaction groups
- Add interactions to groups, or individual drugs
- Interactions API request working
- Browsable list of drug interactions (With Login Only)

**Comment by jmbrunskill** [comment]
![image](https://github.com/msupply-foundation/unified-codes/assets/8287373/19749111-48d3-4198-994e-c8c227bcaefc)

![image](https://github.com/msupply-foundation/unified-codes/assets/8287373/a0d8bb44-5f39-44ee-b28c-5f558b10f715)

**Comment by jmbrunskill** [comment]
![image](https://github.com/msupply-foundation/unified-codes/assets/8287373/6eccebbb-5a3d-486c-a3ab-316b9995c23f)

![image](https://github.com/msupply-foundation/unified-codes/assets/8287373/e07f74c3-cc29-4ac8-b264-52bd95afe29a)

![image](https://github.com/msupply-foundation/unified-codes/assets/8287373/d12b23d8-a94f-4677-8c98-d2e398a75ece)
